# Generated by Django 5.1.3 on 2024-11-05 08:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('segunda_mano', models.BooleanField(default=False)),
                ('caballos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta_bancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=100, unique=True)),
                ('banco', models.CharField(choices=[('CA', 'Caixa'), ('BB', 'BBVA'), ('UN', 'Unicaja'), ('IN', 'ING')], max_length=2)),
                ('Cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='examenDWSdjango.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Voto_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField()),
                ('comentario', models.TextField(max_length=200)),
                ('fecha_hora', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenDWSdjango.cliente')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenDWSdjango.moto')),
            ],
        ),
        migrations.AddField(
            model_name='moto',
            name='votos_usuario',
            field=models.ManyToManyField(related_name='voto', through='examenDWSdjango.Voto_cliente', to='examenDWSdjango.cliente'),
        ),
    ]
