# Generated by Django 5.1.3 on 2024-11-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenDWSdjango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto_cliente',
            old_name='estado',
            new_name='puntuacion',
        ),
    ]
