# Generated by Django 5.1.3 on 2024-11-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenDWSdjango', '0003_alter_voto_cliente_cliente_alter_voto_cliente_moto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta_bancaria',
            old_name='Cliente',
            new_name='cliente',
        ),
    ]
