# Generated by Django 5.1.3 on 2024-11-05 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenDWSdjango', '0004_rename_cliente_cuenta_bancaria_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta_bancaria',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_cliente', to='examenDWSdjango.cliente'),
        ),
    ]
