# Generated by Django 5.1.3 on 2024-11-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenDWSdjango', '0005_alter_cuenta_bancaria_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto_cliente',
            old_name='fecha_hora',
            new_name='fecha_voto',
        ),
    ]
